# Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
#
# This file is part of aimbots-src.
#
# aimbots-src is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# aimbots-src is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with aimbots-src.  If not, see <https://www.gnu.org/licenses/>.

default:
  image: aruw/mcb-2020-gitlab-ci:2021-06-02.1

variables:
  ARTIFACT_PATH: isolated-deploy
  GIT_SUBMODULE_STRATEGY: normal
  DEFAULT_BUILD_ELF_FILE: build/hardware/scons-release/aimbots-src.elf
  DEFAULT_TESTS_BUILD_ELF_FILE: build/tests/scons-fast/aimbots-src-tests.elf
  NUM_JOBS: 4

.verification_except: &verification_except
  - schedules

stages:
  - Build
  - Test
  - Quality
  - Deploy Pages

before_script:
  - python3 -V # Print out python version for debugging

# Quality
# Last stage, but configured to not depend on preceding jobs

clang-format:
  stage: Quality
  needs: []
  script:
    - python3 /run-clang-format.py --clang-format-executable clang-format-10 -r aimbots-src/src/ aimbots-src/test/
  except: *verification_except

"Policy Checks":
  stage: Quality
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - python3 ./taproot-scripts/check_singleton_drivers.py DoNotUse_getDrivers
        -p ./template-project/src/
        -w drivers_singleton.cpp
            drivers_singleton.hpp
            main.cpp

    - python3 ./taproot-scripts/check_license_headers.py
        -p template-project
        -i './**/__init__.py' 'taproot/**/*' 'taproot-scripts/**/*' 'template-project/taproot/**/*' 'docs/**/*' 'template-project/robot-type/robot_type.hpp'
        -o 'Advanced Robotics at the University of Washington'

    - python3 ./taproot-scripts/check_header_guard.py template-project/src template-project/test/

    - ./taproot-scripts/check_taproot_submodule.sh ./template-project ./taproot
  except: *verification_except

# Hidden jobs to be extended for each robot

.hw_build:
  stage: Build
  script:
    - cd aimbots-src
    - python3 $(which scons) build robot=TARGET_$ROBOT -j${NUM_JOBS} additional-ccflags=-Werror
    - python3 $(which scons) size robot=TARGET_$ROBOT -j${NUM_JOBS} additional-ccflags=-Werror > size.txt
    - python3 ../taproot-scripts/parse_metrics.py -i size.txt -o metrics.txt --identifier $ROBOT
    - cp $DEFAULT_BUILD_ELF_FILE ../$ARTIFACT_PATH/aimbots-src-$ROBOT.elf
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$ROBOT-mcb"
    paths:
      - $ARTIFACT_PATH/*
    expire_in: 2 weeks
    reports:
      metrics: metrics.txt

.sim_build:
  stage: Build
  script:
    - cd aimbots-src
    - python3 $(which scons) build-sim profile=fast robot=TARGET_$ROBOT -j${NUM_JOBS}

.test_build:
  stage: Build
  script:
    - cd aimbots-src
    - python3 $(which scons) build-tests profile=fast robot=TARGET_$ROBOT -j${NUM_JOBS}
  artifacts:
    paths:
      - aimbots-src/$DEFAULT_TESTS_BUILD_ELF_FILE

.test_run:
  stage: Test
  script:
    - cd aimbots-src
    - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all $DEFAULT_TESTS_BUILD_ELF_FILE


# Standard

"Standard: build for hardware":
  extends:
    - .hw_build
  variables:
    ROBOT: STANDARD

"Standard: build for sim":
  extends:
    - .sim_build
  variables:
    ROBOT: STANDARD

"Standard: build for tests":
  extends:
    - .test_build
  variables:
    ROBOT: STANDARD

"Standard: run tests":
  # The Standard's test run is also evaluated for code coverage and used as the repo-level coverage report
  needs: [ "Standard: build for tests" ]
  dependencies: [ "Standard: build for tests" ]
  extends:
    - .test_run
  variables:
    ROBOT: STANDARD
  script:
    - cd aimbots-src
    - valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all $DEFAULT_TESTS_BUILD_ELF_FILE
    - cd .. && gcovr -g --xml > cobertura.xml
    - 'sed -i "s=<source>.</source>=<source>./aimbots-src</source>=g" cobertura.xml'
    - 'sed -i "s;filename=\";filename=\"aimbots-src/;g" cobertura.xml'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-standard-tests"
    reports:
      cobertura: cobertura.xml
    expire_in: 2 weeks

# Drone

"Drone: build for hardware":
  extends:
    - .hw_build
  variables:
    ROBOT: DRONE

"Drone: build for sim":
  extends:
    - .sim_build
  variables:
    ROBOT: DRONE

"Drone: build for tests":
  extends:
    - .test_build
  variables:
    ROBOT: DRONE

"Drone: run tests":
  needs: [ "Drone: build for tests" ]
  dependencies: [ "Drone: build for tests" ]
  extends:
    - .test_run
  variables:
    ROBOT: DRONE


# Engineer

"Engineer: build for hardware":
  extends:
    - .hw_build
  variables:
    ROBOT: ENGINEER

"Engineer: build for sim":
  extends:
    - .sim_build
  variables:
    ROBOT: ENGINEER

"Engineer: build for tests":
  extends:
    - .test_build
  variables:
    ROBOT: ENGINEER

"Engineer: run tests":
  needs: [ "Engineer: build for tests" ]
  dependencies: [ "Engineer: build for tests" ]
  extends:
    - .test_run
  variables:
    ROBOT: ENGINEER


# Hero

"Hero: build for hardware":
  extends:
    - .hw_build
  variables:
    ROBOT: HERO

"Hero: build for sim":
  extends:
    - .sim_build
  variables:
    ROBOT: HERO

"Hero: build for tests":
  extends:
    - .test_build
  variables:
    ROBOT: HERO

"Hero: run tests":
  needs: [ "Hero: build for tests" ]
  dependencies: [ "Hero: build for tests" ]
  extends:
    - .test_run
  variables:
    ROBOT: HERO


# Sentry

"Sentry: build for hardware":
  extends:
    - .hw_build
  variables:
    ROBOT: SENTRY

"Sentry: build for sim":
  extends:
    - .sim_build
  variables:
    ROBOT: SENTRY

"Sentry: build for tests":
  extends:
    - .test_build
  variables:
    ROBOT: SENTRY

"Sentry: run tests":
  needs: [ "Sentry: build for tests" ]
  dependencies: [ "Sentry: build for tests" ]
  extends:
    - .test_run
  variables:
    ROBOT: SENTRY


# Pages deploy

pages:
  image: alpine
  stage: Deploy Pages
  variables:
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - apk update
    - apk add py-pip python3-dev
    - apk add make
    - apk add --no-cache g++ gcc libxml2-dev libxslt-dev
    - pip3 install lxml
    - pip3 install sphinx breathe exhale
    - pip install sphinx_rtd_theme
    - apk add doxygen
  script:
    - cd docs && make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - develop
  except:
    - schedules
